name: Build, test and analyze

on:
  pull_request:
    branches: [ master ]
  workflow_call:

permissions:
  contents: read
  security-events: write

jobs:

  # Run linter to ensure new code respect coding rules
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
        with:
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 17
      - name: Setup metrics
        run: npm ci
      - name: Check contributions requirements
        run: npm run test-contrib
        env:
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
      - name: Run linter
        run: npm run linter

  # Build docker image from branch and run tests
  build:
    name: Build and test
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - name: Format code with dprint
        run: |
          curl -fsSL https://dprint.dev/install.sh --output /tmp/dprint-install.sh
          sh /tmp/dprint-install.sh
          rm /tmp/dprint-install.sh
          cp /home/runner/.dprint/bin/dprint /usr/local/bin/dprint
          npm install -g eslint
          dprint fmt --config .github/config/dprint.json
      - name: Build lowlighter/metrics
        env:
          HEAD_REF: ${{ github.head_ref || 'master' }}
        run: |
          SAFE_TAG=$(echo "$HEAD_REF" | sed 's/\//-/g')
          docker build -t "lowlighter/metrics:$SAFE_TAG" .
      - name: Run tests
        env:
          HEAD_REF: ${{ github.head_ref || 'master' }}
        run: |
          SAFE_TAG=$(echo "$HEAD_REF" | sed 's/\//-/g')
          docker run --rm --entrypoint="" "lowlighter/metrics:$SAFE_TAG" npm run test-metrics

  # Run CodeQL on branch
  analyze:
    name: Analyze code
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - name: Setup CodeQL
        uses: github/codeql-action/init@b8d3b6e8af63cde30bdc382c0bc28114f4346c88 # v2
        with:
          languages: javascript
          config-file: ./.github/config/codeql.yml
      - name: Analyze code
        uses: github/codeql-action/analyze@b8d3b6e8af63cde30bdc382c0bc28114f4346c88 # v2
